#+TITLE: 一般评分标准
#+LANGUAGE: zh-CN
#+OPTIONS: toc:nil num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage[fontset=none]{ctex}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont{Times New Roman}
#+LATEX_HEADER: \setCJKmainfont{FZShuSong-Z01S}
#+DESCRIPTION: 2025年英语（一）考纲PDF第43—46页；通用评分细则、原则与档次标准。

* 翻译评分细则
(1) 如果译文与原文意思有明显不同，该句得分最多不超过0.5分。

(2) 如果考生就一个题目提供了两个或两个以上的译文，并均正确，按正确译文给分；如果其中一个译文有错，按错误译文给分。

(3) 译文中错别字按每题累计扣分。三个及以上错别字扣0.5分，否则不扣分。

* 写作评分原则和方法
(1) 一般评分标准适用于A、B两节。但根据两节不同的考查要点，评分时应有不同的侧重点。

A节作文的评分重点在于内容要点的覆盖、文章的组织连贯性、语言的准确性、文体格式和语体的恰当性。对语法结构和词汇多样性的要求将根据具体试题做调整。

B节作文的评分重点在于内容要点的覆盖和阐述、文章的组织连贯性、语法结构和词汇的多样性及语言的准确性。

允许在作文中使用指导语或提示信息中的个别关键词语，但使用其中部分或整个语句的，将被酌情扣分。

(2) 评分时，先根据文章的内容和语言确定其所属档次，然后按该档次的要求来给分。

(3) A节作文的词数要求是100词左右；B节作文的词数要求是160～200词。文章长度不符合要求的，酌情扣分。

(4) 拼写与标点符号是反映语言准确性的一个方面。评分时，要视其对交际的影响程度予以考虑。英、美拼写及词汇用法均可接受。

(5) 如书写较差，以致影响读者理解，将分数降低一个档次。


* 写作一般评分标准
** 第五档 A节 (9～10分) B节 (17～20分)

很好地完成了试题规定的任务：

·包含并有效阐述所有内容要点；

·使用了丰富的语法结构和词汇；

·语法结构和词汇准确，错误极少；

·有效地使用了多种衔接手段，内容连贯、流畅，层次清晰；

·文体格式和语体恰当贴切。

对目标读者完全产生了预期的效果。

** 第四档 A节 (7～8分) B节 (13～16分)

较好地完成了试题规定的任务：

·包含所有内容要点，少数要点未能有效阐述；

·使用了较丰富的语法结构和词汇；

·语言基本准确，只有在试图使用较复杂结构或较高级词汇时才有个别错误；

·比较有效地使用了一些衔接手段，内容较连贯，层次较清晰；

·文体格式和语体较恰当。

对目标读者产生了预期的效果。

** 第三档 A节 (5～6分) B节 (9～12分)

基本完成了试题规定的任务：

·虽漏掉一些内容，但包含多数内容要点；

·语法结构和词汇基本满足任务的需求；

·存在一些语法结构或词汇错误，但基本不影响理解；

·使用了简单的衔接手段，内容基本连贯，层次基本清晰；

·文体格式和语体基本合理。

对目标读者基本产生了预期的效果。

** 第二档 A节 (3～4分) B节 (5～8分)

未能按要求完成试题规定的任务：

·漏掉或未能有效阐述一些内容要点，写了一些无关内容；

·语法结构单调，词汇有限；

·存在较多语法结构或词汇错误，影响理解；

·未采用必要的衔接手段，内容缺乏连贯性；

·文体格式和语体不恰当。

未能清楚地把信息传达给读者。

** 第一档 A节 (1～2分) B节 (1～4分)

未完成试题规定的任务：

·明显遗漏主要内容，写了许多不相关的内容；

·语法结构很单调，词汇很有限；

·语言错误很多，内容很难理解；

·未使用任何衔接手段，内容不连贯，缺少组织、分段；

·无文体格式和语体概念。

未能把信息传达给读者。

** 零档 (0分)

所传达的信息或所用语言太少，无法评价；内容与要求无关或无法辨认。
